# Configuration for your GitHub profile

profile:
  # Name displayed on your profile
  name: Jiyu 

  # Avatar image (URL or username/repository:branch)
  # Example URL: https://example.com/avatar.png
  # Example repository: user/repo:branch
  avatar_url: https://inbuzz.co.uk/wp-content/uploads/2024/02/HYUNJUN-HUB.png

  # Bio displayed on your profile
  bio: |
    Hello! I'm a passionate Developer and Graphic designer from South Korea.

  # Website link (optional)
  # Example: https://example.com
  website_url: https://jiyubear.co

  # Location (optional)
  location: Amsterdam, Netherlands 

  # GitHub username
  # Example: octocat
  github_username: Hyeongikas

